apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
  annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource
spec:
  version: v1.8.2
  server:
    route:
      enabled: true
  dex:
    image: ghcr.io/dexidp/dex
    openShiftOAuth: true
    version: v2.27.0
  resourceCustomizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, developer, role:developer
    scopes: '[groups]'
  initialRepositories: |
    - name: cluster-config
      type: git
      url: https://github.com/ocp-tigers/acm-lab-deploy
