apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

resources:
- namespace.yaml
- obs-secret.yaml
- pull-secret.yaml
- multiclusterobservability.yaml
