apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: thanos-object-storage
spec:
  encryptedData:
    thanos.yaml: AgCIiqBVFpMiMPUVfMXZriTDiGMUC4rbJLRIaxMnbS5Q02T7vpiLPhl/C/JSwmtupA+zDQvhndxf8s/j5LX414O7CNd2gB0V5lGNKYxMdAZW3LKglvIesV0wP2CXJe2O4p6DSMA6GeyNABgQ4H1PCwILFXYuuJKBoFUOkKpOC3NrKCzqvOKuZ25JPIw3Xuo2it7Tt7EndW6HF0hf620Qpp7ybL/X1nD/VRZlOuCy9sCBWeF5Pdi1C+Ohlc0azjKEM8BlbZVpI5H7XRogTFHubm2lpPMZ9ZNwS9m3smTjm3+DP1mItepsF4+VOwtdCmqTB1Tqf5qtUDV28pd5i82ZPkgXNVin1LJWTBaB9sQC4kBCrX1F8SfpJwMnKtK4xoyjJ5K9gMCDPyt1pmDsc6THh2zWkRckL/PYFr+szm8hYq4NG+m8OxxV2fk2hVJnM+d6XfBnP79DOFTgHO4inWPL5253OxLGGJN6s3yXjFB4u+51Yy3TUTf93dtfRFvZDqTU47/FSwWe2s8H3v7M5V7dFlXEoxr+MGWSX9yf+gaaFY4e0FPtIyHJHhzpC6C+5qT9IYuPoPB7vlDv2cWeQk/TxsVNQHXjWUVhl1NA1KF7Wq8c3iDhGFtHQj7NpcrBggHi/CNu/Y6BkHJ4hd9uXIULg+fL3AiIs4jDlnOWVxGKZ2+ATZ97bGLOwGFO1CKXINNK3pHZMoa7NZGDoS2rroKlwDeERgRwMleIqyhIZGFAAmeNYanhGyHYtIswv3FG/jCZdvZqnLvXG8tcht0UQL2vIaHDWPN5xRZ9zcCJNBFaBY54GK7xLIM2t1YETcZhKvxdGCm9qpyp5bql/uaSL1Oo+BARLJmBbcEAmQCNiZMnj6CvxJ34gsegQDd3TPDsCRTTruhBuhy2CqNlwD7HsmewjESLYs87z2lNOL9t0ZZhYLSeJZInffVlzQ/Dew+JHiKTfCyHU14ffISIZ0a73dHke7pwhDdzQiOl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: thanos-object-storage
    type: Opaque

