apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: thanos-object-storage
spec:
  encryptedData:
    thanos.yaml: AgCUen9zIoGivIrPtNC9CeaP7dsh6A1QlfJrZpp1jJPJgFXQk46aBv0z1pjBkjXwfBuLbz83e9r2naZZGl/ZC5QekkNNLpwkQOupMrPgQtcd4vNprNLBGHRe7eeoSf3hUhJmy5WNSrP4WS30hH87JlhLnnO8qr8GwAu10fHyXPoGwf04pH4m0Lhc5SpuKmeBqgBApXH2twHu5tXo52gQRuA6X25Kwn9A5yKMNwDHaYWb0jUmjjPw7iYf4nSi5KB6ZgcQIHdtjX+pVOGMw1fyy5nfZGJ8XdBbPYVzE01kJiSZPaJooxqKu1gRlopJUQQtRVBEqnfKnTrLSDfAg+WAaNneRhP2NgjxQzy77/wJKOGyumzHejK1hul50u0RDjOgRKtesdj0ooun9NYxhQJ/k5VLtS3imxnCgXjW2wWk67TT+QB5/zcWCSnR8F/kIGRkb0h+wLVH6uQCQJpvAtDNMgmHC9RNXDnwvB+viHUg25dUetF3XDADecBacTTpSauU1bVeDfvXWn51QuQisoYcbcHckSrbg0Aqj+DKTreXqKku8NIUHxGn7WKyF492MK6RVrAu9C+F4SnHmiuGQUG1BL1Ro9A+XvF840EiSMDi7uekLaHAE+Nb/7UblzDM1yE1F9aEI5orGkbGRKRRzIBg3ROqi3IXhIC9i8IlclCyITMMrr2LMIno4az2finNMZVy/UCz6ojSCrvZeni6zmN/eycgQKv73CPAf5x/5C7qzI6tUhw1XKvFVWAXVndQZq4Y2qWW4/hRHEm3VZtUP7Uwg4ZSZW9RFUgW1lrls3pMTuu3ekFz28Klt2NLWTyJr8R6hSsTlDvDX1yf735OOPJAGBi6qcSVkqgFJdMw2oyh91gjBGGbJuEafsaIh5AvQONGA4qwGS8dz9KqoM0iv7BOqfBzWOCRmK1Hpt0N2KkkV/iJzLUbHO9XLjm2Zj+uWIA3ch3taKiT1XM1XCqdomzJ4EU7ZpDEIypR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: thanos-object-storage
    type: Opaque

