apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: thanos-object-storage
spec:
  encryptedData:
    thanos.yaml: AgAkv5JzILz3TKvrhZXMth5+50OhrhiTmQLP1RWR+jiWOBYy8EsSOD/pQsDTe+J659xPhq7xGd66tT/T+lJT0e9bTZv+zNeFGbNPqN/A3aU/9UndEM/0BO/rP0eARtmnZ8TatNFsRnyQjQ0HAJIdTUf+LeWhMQBdGo0+HF/0Rq/SAXHsEf0tLZmCjcydCYO9hD9o8kt05crqhEfA0OsjueILDPaZsL9N1P/Bi+SZ9v+Upd7Qm3arvkFagkyMzVtUhXyMObHJPgpLMlI4z8SohkFLwMeaYrjxVGsdkprmJDxDUW15Qn7s5JZ3jSM7zsca6RhzC4UuykGvHtCCyrLzdizTLME/KCTDzU93g8/urQpOTHT/qa9aK0NqFfGHcCSl7MCWMckj05YTW2SOe4dBUXm0wdIB/wiIV8wdkIO5dlIzKVjeUcOWT6QAkGFpMKzvD+yBsLObCO5LHcUwTUYHtqlRQpAKQk9l1uK30p2PkAn7CRbIQIcgLAi7GxPGhSB6GkkSpqyeoE7D9xKQgFiOY5Wz2nqGU2EB9Eahjrv18ff754W/UzLHmTp+XkjoXpsST0kJqLLacW1TREn+9xZkV6aYbvfUpj14k87MSNKP/KqcNS/ZU0+iGHMfNEZ3Gd+1d/6yDNzE8gZOl5KkGY3YJXbxDRN/qMozkyoFje3nGJatDeb9r5o91aRiOv63fsQlTnnPtc/82q05+MO7HMTgqhJQZGuRE1AEjJJGIZxMn3opqpe5dwLpemM/Jmf/NsAevbuHz0hJp8gI1fgyewn2iyy4rjLuhcLDoMRnGlE7kZE5v/ZjBIJFiOhGiKHj1E4fwKQMPCHfVCXirzUrGOu3OqnQF1kZFjVoI0N5anlS1aQAwD22NYFVpVEMAObXFzcC/ud5YSSLuXsR+/091KS2N9vBPpySIX3eepeEVlJqe06Ka/nubiXz7ohCrx4wiYqsDtYf8JEab+dD9Pm8UgbzO8WUoeA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: thanos-object-storage
    type: Opaque

