apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-container-security
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: acm-lab-config
  source:
    path: manifests/container-security-operator/base
    repoURL: https://github.com/manuvaldi/acm-lab-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      source:
        path: manifests/container-security-operator/base
        repoURL: https://github.com/manuvaldi/acm-lab-deploy
        targetRevision: master
